### ISSUE TITLE
help to delete content at linux.cn

### ISSUE THREAD

**Issue by aratic** [locez/LC-Contributor#1]
Hi Admin,

I'm the user https://linux.cn/space/14795/

quite long ago I leave an comment at page https://linux.cn/article-1970-1.html
referring https://linux.cn/forum.php?mod=viewthread&tid=11535&page=1#pid39968

I thought it may leak some information on public space
could you please help to delete the comment

sorry for bothering

technically, i may support you to make crawler for acquiring news if that could compensate

Thanks

**Comment by locez** [comment]
Ok，I will delete it later.Thanks for attention

**Comment by aratic** [comment]
many thanks, but seems google / bing / baidu all got cached pages
not easy to force them recrawk

thanks a lot for your kind assist :)
